create:
  handler: ./create.handler
  events:
    - httpApi:
        path: /{itemType}
        method: post
  environment:
    TABLE_NAME: ${self:custom.tableName}
    REGION: ${self:provider.region}
list:
  handler: ./list.handler
  events:
    - httpApi:
        path: /{itemType}
        method: get
read:
  handler: ./read.handler
  events:
    - httpApi:
        path: /{itemType}/{itemId}
        method: get
update:
  handler: ./update.handler
  events:
    - httpApi:
        path: /{itemType}/{itemId}
        method: put
delete:
  handler: ./delete.handler
  events:
    - httpApi:
        path: /{itemType}/{itemId}
        method: delete
